INSERT INTO EMPLOYEE VALUES(101, 'Amar Rane', 'C');
INSERT INTO EMPLOYEE VALUES(102, 'Kedar Tokekar', 'Java'); 
INSERT INTO EMPLOYEE VALUES(103, 'Siddharth Singh', 'Java');
INSERT INTO EMPLOYEE VALUES(104, 'Anthony Sharma', 'C++');
INSERT INTO EMPLOYEE VALUES(105, 'Akbar Tripathi', 'C#');